### ISSUE TITLE
What is the correct format of the config file?

### ISSUE THREAD

**Issue by hmpf** [upciti/wheel2deb#49]
I've tried putting the following in a file `wheel2deb.yml`:

```
---                                                                                       
maintainer_name: 'Testuser'                                                     
maintainer_email: 'testuser@example.com'                                            
...
```

.. and run wheel2deb like so: `wheel2deb convert -c ./wheel2deb.yml`

The result in `output/` is not a .deb but a directory with `debian/`, `entrypoints/`, `missing.txt` and `src/` in it. If I don't add the `-c`-flag I do get a .deb.

**Comment by fyhertz** [comment]
You are missing a key with a regex to tell wheel2deb which wheels it should apply your config to:

Here is an example:

```yaml
.:
  maintainer_name: 'Testuser'                            
  maintainer_email: 'testuser@example.com' 

PyTurboJPEG:
  revision: 2
  depends:
    - libturbojpeg0

sounddevice:
  revision: 2
  depends:
    - libportaudio2
```
```

The "." in ".:" is a regex that will match all wheels, i.e. wheel2deb will apply the specified maintainer_name to all wheels.

You can be more specific: "PyTurboJPEG" will only match wheel names starting with "PyTurboJPEG", e.g. PyTurboJPEG-1.7.0-py3-none-any.whl
